# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: security.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'security.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esecurity.proto\x12\x08zeropass\"G\n\x10SignatureRequest\x12\x12\n\npublic_key\x18\x01 \x01(\x0c\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"9\n\x11SignatureResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\"\x1d\n\x0cTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\">\n\rTokenResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12\r\n\x05roles\x18\x03 \x03(\t\"E\n\x0bRiskRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12\x12\n\nip_address\x18\x03 \x01(\t\"1\n\x0cRiskResponse\x12\r\n\x05score\x18\x01 \x01(\x02\x12\x12\n\nrisk_level\x18\x02 \x01(\t2\xde\x01\n\x0fSecurityService\x12J\n\x0fVerifySignature\x12\x1a.zeropass.SignatureRequest\x1a\x1b.zeropass.SignatureResponse\x12@\n\rValidateToken\x12\x16.zeropass.TokenRequest\x1a\x17.zeropass.TokenResponse\x12=\n\x0cGetRiskScore\x12\x15.zeropass.RiskRequest\x1a\x16.zeropass.RiskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'security_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIGNATUREREQUEST']._serialized_start=28
  _globals['_SIGNATUREREQUEST']._serialized_end=99
  _globals['_SIGNATURERESPONSE']._serialized_start=101
  _globals['_SIGNATURERESPONSE']._serialized_end=158
  _globals['_TOKENREQUEST']._serialized_start=160
  _globals['_TOKENREQUEST']._serialized_end=189
  _globals['_TOKENRESPONSE']._serialized_start=191
  _globals['_TOKENRESPONSE']._serialized_end=253
  _globals['_RISKREQUEST']._serialized_start=255
  _globals['_RISKREQUEST']._serialized_end=324
  _globals['_RISKRESPONSE']._serialized_start=326
  _globals['_RISKRESPONSE']._serialized_end=375
  _globals['_SECURITYSERVICE']._serialized_start=378
  _globals['_SECURITYSERVICE']._serialized_end=600
# @@protoc_insertion_point(module_scope)
