# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import security_pb2 as security__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in security_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SecurityServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VerifySignature = channel.unary_unary(
                '/zeropass.SecurityService/VerifySignature',
                request_serializer=security__pb2.SignatureRequest.SerializeToString,
                response_deserializer=security__pb2.SignatureResponse.FromString,
                _registered_method=True)
        self.ValidateToken = channel.unary_unary(
                '/zeropass.SecurityService/ValidateToken',
                request_serializer=security__pb2.TokenRequest.SerializeToString,
                response_deserializer=security__pb2.TokenResponse.FromString,
                _registered_method=True)
        self.GetRiskScore = channel.unary_unary(
                '/zeropass.SecurityService/GetRiskScore',
                request_serializer=security__pb2.RiskRequest.SerializeToString,
                response_deserializer=security__pb2.RiskResponse.FromString,
                _registered_method=True)


class SecurityServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def VerifySignature(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRiskScore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SecurityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VerifySignature': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifySignature,
                    request_deserializer=security__pb2.SignatureRequest.FromString,
                    response_serializer=security__pb2.SignatureResponse.SerializeToString,
            ),
            'ValidateToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateToken,
                    request_deserializer=security__pb2.TokenRequest.FromString,
                    response_serializer=security__pb2.TokenResponse.SerializeToString,
            ),
            'GetRiskScore': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRiskScore,
                    request_deserializer=security__pb2.RiskRequest.FromString,
                    response_serializer=security__pb2.RiskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zeropass.SecurityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('zeropass.SecurityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SecurityService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def VerifySignature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zeropass.SecurityService/VerifySignature',
            security__pb2.SignatureRequest.SerializeToString,
            security__pb2.SignatureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zeropass.SecurityService/ValidateToken',
            security__pb2.TokenRequest.SerializeToString,
            security__pb2.TokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRiskScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zeropass.SecurityService/GetRiskScore',
            security__pb2.RiskRequest.SerializeToString,
            security__pb2.RiskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
